name: OpenSSL Crypto-policies Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y openssl openssl-devel tcpdump net-tools wireshark-cli ShellCheck

    - name: Lint shell scripts
      run: |
        shellcheck *.sh

    - name: Setup test environment
      run: |
        ./setup.sh

    - name: Run tests
      run: |
        source ./work/test_env.sh
        ./test.sh

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          work/capture/*.pcap
          work/**/*.log
        retention-days: 7
