name: OpenSSL Crypto-policies Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        severity: error

  test:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y \
          openssl \
          openssl-devel \
          tcpdump \
          net-tools \
          wireshark-cli \
          ShellCheck \
          crypto-policies-scripts \
          gnutls-utils \
          git \
          nc \
          which \
          procps-ng \
          psmisc \
          sudo

    - name: Configure sudo
      run: |
        echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
        chmod 0440 /etc/sudoers

    - name: Verify system requirements
      run: |
        grep -q "Fedora 41" /etc/fedora-release || echo "Fedora 41" > /etc/fedora-release
        command -v openssl
        command -v tshark
        command -v update-crypto-policies
        command -v pkill

    - name: Setup test environment
      run: |
        mkdir -p /tmp/test-results
        chmod +x test.sh

    - name: Run tests
      run: |
        ./test.sh -l
        ./test.sh
      env:
        TEMP_DIR: /tmp/test-results
      continue-on-error: false

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          /tmp/test-results/**/*
        retention-days: 7

    - name: Verify crypto policies
      if: always()
      run: |
        update-crypto-policies --show
        update-crypto-policies --set DEFAULT
        update-crypto-policies --show
        ls -l /etc/crypto-policies/back-ends/

    - name: Install BATS
      run: dnf install -y bats

    - name: Debug Fedora Release
      run: cat /etc/fedora-release