name: OpenSSL Crypto-policies Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --privileged --cap-add=SYS_PTRACE --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y openssl openssl-devel tcpdump net-tools wireshark-cli ShellCheck crypto-policies-scripts gnutls-utils git

    - name: Lint shell scripts
      run: |
        shellcheck -x test.sh

    - name: Setup test environment
      run: |
        mkdir -p /tmp/test-results
        chmod +x test.sh

    - name: Run tests
      run: |
        ./test.sh --list  # List available tests
        ./test.sh  # Run all tests
      env:
        TEMP_DIR: /tmp/test-results

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          /tmp/test-results/capture.pcap
          /tmp/test-results/*.log
          /tmp/test-results/certs/*
        retention-days: 7

    - name: Verify crypto policies
      run: |
        update-crypto-policies --show
        update-crypto-policies --set DEFAULT
        update-crypto-policies --show  # Verify change
        ls -l /etc/crypto-policies/back-ends/
        for backend in /etc/crypto-policies/back-ends/*; do
          echo "=== $backend ==="
          cat "$backend"
        done